I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 172, in script
    d "you ready to play Pichael?"
Exception: Sayer 'd' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 172, in script
    d "you ready to play Pichael?"
  File "/Users/arajo/renpy_games/renpy/ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/arajo/renpy_games/renpy/ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'd' is not defined.

Darwin-18.7.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
derek 1.0
Tue Sep 22 19:18:18 2020
